### ISSUE TITLE
Nimble problems

### ISSUE THREAD

**Issue by Laurin08** [Mystfit/ESP32-BLE-CompositeHID#21]
I get several errors while compiling the example gamepad code. I think the problem is the NimBLE library. Which version do you guys use? With the older version (2.0.0) I got less errors but still something:

/Users/laurinmichel/Documents/Arduino/libraries/ESP32-BLE-CompositeHID/GamepadDevice.cpp: In member function 'uint8_t GamepadDevice::specialButtonBitPosition(uint8_t)':
/Users/laurinmichel/Documents/Arduino/libraries/ESP32-BLE-CompositeHID/GamepadDevice.cpp:343:20: error: 'invalid_argument' is not a member of 'std'
343 | throw std::invalid_argument("Index out of range");
| ^~~~~~~~~~~~~~~~
/Users/laurinmichel/Documents/Arduino/libraries/ESP32-BLE-CompositeHID/GamepadDevice.cpp:6:1: note: 'std::invalid_argument' is defined in header ''; did you forget to '#include '?
5 | #include "esp32-hal-log.h"
+++ |+#include
6 | #define LOG_TAG "GamepadDevice"

exit status 1

Compilation error: exit status 1

**Comment by cflixdev-projects** [comment]
You need to download these commit versions but before u should delete them from Arduino Library Manager:
## Dependencies
 - Nimble-Arduino. Use the latest Github version from commit [a79941c](https://github.com/h2zero/NimBLE-Arduino/commit/a79941cc9e77ed60136ee385b1c73d89c847bd94) onwards. Do not use 1.4.2 from the Arduino library manager.
 -  Callback. Available from the Arduino library manager or [here](https://github.com/tomstewart89/Callback).

**Comment by Laurin08** [comment]
Hey 
Thanks for your answer but I already installed the Callback library and the new Nimble version has commit [a79941c](https://github.com/h2zero/NimBLE-Arduino/commit/a79941cc9e77ed60136ee385b1c73d89c847bd94) already integrated, if I saw that right.
if I use the newest nimble version (2.1.2) I get even more errors. 
I don't really know were the issue could be. I also tried it on another laptop where only the needed libraries were installed.



the errors with version 2.1.2:

```
/Users/laurinmichel/Documents/Arduino/libraries/ESP32-BLE-CompositeHID/GamepadDevice.cpp: In member function 'virtual void GamepadDevice::init(NimBLEHIDDevice*)':
/Users/laurinmichel/Documents/Arduino/libraries/ESP32-BLE-CompositeHID/GamepadDevice.cpp:147:23: error: 'class NimBLEHIDDevice' has no member named 'inputReport'; did you mean 'getInputReport'?
  147 |     auto input = hid->inputReport(_config.getReportId());
      |                       ^~~~~~~~~~~
      |                       getInputReport
/Users/laurinmichel/Documents/Arduino/libraries/ESP32-BLE-CompositeHID/GamepadDevice.cpp:150:24: error: 'class NimBLEHIDDevice' has no member named 'outputReport'; did you mean 'getOutputReport'?
  150 |     auto output = hid->outputReport(_config.getReportId());
      |                        ^~~~~~~~~~~~
      |                        getOutputReport
/Users/laurinmichel/Documents/Arduino/libraries/ESP32-BLE-CompositeHID/GamepadDevice.cpp: In member function 'uint8_t GamepadDevice::specialButtonBitPosition(uint8_t)':
/Users/laurinmichel/Documents/Arduino/libraries/ESP32-BLE-CompositeHID/GamepadDevice.cpp:343:20: error: 'invalid_argument' is not a member of 'std'
  343 |         throw std::invalid_argument("Index out of range");
      |                    ^~~~~~~~~~~~~~~~
/Users/laurinmichel/Documents/Arduino/libraries/ESP32-BLE-CompositeHID/GamepadDevice.cpp:6:1: note: 'std::invalid_argument' is defined in header '<stdexcept>'; did you forget to '#include <stdexcept>'?
    5 | #include "esp32-hal-log.h"
  +++ |+#include <stdexcept>
    6 | #define LOG_TAG "GamepadDevice"
/Users/laurinmichel/Documents/Arduino/libraries/ESP32-BLE-CompositeHID/BleConnectionStatus.cpp: In member function 'virtual void BleConnectionStatus::onConnect(NimBLEServer*, NimBLEConnInfo&)':
/Users/laurinmichel/Documents/Arduino/libraries/ESP32-BLE-CompositeHID/BleConnectionStatus.cpp:9:31: error: invalid use of incomplete type 'class NimBLEConnInfo'
    9 |     pServer->updateConnParams(connInfo.getConnHandle(), 6, 7, 0, 600);
      |                               ^~~~~~~~
In file included from /Users/laurinmichel/Documents/Arduino/libraries/ESP32-BLE-CompositeHID/BleConnectionStatus.h:9,
                 from /Users/laurinmichel/Documents/Arduino/libraries/ESP32-BLE-CompositeHID/BleConnectionStatus.cpp:1:
/Users/laurinmichel/Documents/Arduino/libraries/NimBLE-Arduino/src/NimBLEServer.h:44:7: note: forward declaration of 'class NimBLEConnInfo'
   44 | class NimBLEConnInfo;
      |       ^~~~~~~~~~~~~~
/Users/laurinmichel/Documents/Arduino/libraries/ESP32-BLE-CompositeHID/BleCompositeHID.cpp: In member function 'void BleCompositeHID::setBatteryLevel(uint8_t)':
/Users/laurinmichel/Documents/Arduino/libraries/ESP32-BLE-CompositeHID/BleCompositeHID.cpp:147:25: error: 'class NimBLEHIDDevice' has no member named 'batteryLevel'; did you mean 'setBatteryLevel'?
  147 |             this->_hid->batteryLevel()->notify();
      |                         ^~~~~~~~~~~~
      |                         setBatteryLevel
/Users/laurinmichel/Documents/Arduino/libraries/ESP32-BLE-CompositeHID/BleCompositeHID.cpp: In static member function 'static void BleCompositeHID::taskServer(void*)':
/Users/laurinmichel/Documents/Arduino/libraries/ESP32-BLE-CompositeHID/BleCompositeHID.cpp:221:36: error: 'class NimBLEHIDDevice' has no member named 'reportMap'; did you mean 'setReportMap'?
  221 |     BleCompositeHIDInstance->_hid->reportMap(&customHidReportDescriptor[0], hidReportDescriptorSize);
      |                                    ^~~~~~~~~
      |                                    setReportMap
/Users/laurinmichel/Documents/Arduino/libraries/ESP32-BLE-CompositeHID/BleCompositeHID.cpp:224:36: error: 'class NimBLEHIDDevice' has no member named 'manufacturer'; did you mean 'setManufacturer'?
  224 |     BleCompositeHIDInstance->_hid->manufacturer()->setValue(BleCompositeHIDInstance->deviceManufacturer);
      |                                    ^~~~~~~~~~~~
      |                                    setManufacturer
/Users/laurinmichel/Documents/Arduino/libraries/ESP32-BLE-CompositeHID/BleCompositeHID.cpp:267:36: error: 'class NimBLEHIDDevice' has no member named 'pnp'
  267 |     BleCompositeHIDInstance->_hid->pnp(vidSource, vid, pid, guidVersion);
      |                                    ^~~
/Users/laurinmichel/Documents/Arduino/libraries/ESP32-BLE-CompositeHID/BleCompositeHID.cpp:268:36: error: 'class NimBLEHIDDevice' has no member named 'hidInfo'; did you mean 'setHidInfo'?
  268 |     BleCompositeHIDInstance->_hid->hidInfo(0x00, 0x01);
      |                                    ^~~~~~~
      |                                    setHidInfo
/Users/laurinmichel/Documents/Arduino/libraries/ESP32-BLE-CompositeHID/BleCompositeHID.cpp:280:65: error: 'class NimBLEHIDDevice' has no member named 'hidService'; did you mean 'getHidService'?
  280 |     pAdvertising->addServiceUUID(BleCompositeHIDInstance->_hid->hidService()->getUUID());
      |                                                                 ^~~~~~~~~~
      |                                                                 getHidService
/Users/laurinmichel/Documents/Arduino/libraries/ESP32-BLE-CompositeHID/GamepadConfiguration.cpp: In member function 'virtual size_t GamepadConfiguration::makeDeviceReport(uint8_t*, size_t) const':
/Users/laurinmichel/Documents/Arduino/libraries/ESP32-BLE-CompositeHID/GamepadConfiguration.cpp:52:45: error: 'USAGE_PAGE' was not declared in this scope
   52 |     tempHidReportDescriptor[reportSize++] = USAGE_PAGE(1); //0x05;
      |                                             ^~~~~~~~~~
/Users/laurinmichel/Documents/Arduino/libraries/ESP32-BLE-CompositeHID/GamepadConfiguration.cpp:56:45: error: 'USAGE' was not declared in this scope
   56 |     tempHidReportDescriptor[reportSize++] = USAGE(1); //0x09;
      |                                             ^~~~~
/Users/laurinmichel/Documents/Arduino/libraries/ESP32-BLE-CompositeHID/GamepadConfiguration.cpp:60:45: error: 'COLLECTION' was not declared in this scope
   60 |     tempHidReportDescriptor[reportSize++] = COLLECTION(1); //0xa1;
      |                                             ^~~~~~~~~~
/Users/laurinmichel/Documents/Arduino/libraries/ESP32-BLE-CompositeHID/GamepadConfiguration.cpp:64:49: error: 'REPORT_ID' was not declared in this scope
   64 |         tempHidReportDescriptor[reportSize++] = REPORT_ID(1);
      |                                                 ^~~~~~~~~
/Users/laurinmichel/Documents/Arduino/libraries/ESP32-BLE-CompositeHID/GamepadConfiguration.cpp:74:53: error: 'LOGICAL_MINIMUM' was not declared in this scope
   74 |             tempHidReportDescriptor[reportSize++] = LOGICAL_MINIMUM(1);//0x15;
      |                                                     ^~~~~~~~~~~~~~~
/Users/laurinmichel/Documents/Arduino/libraries/ESP32-BLE-CompositeHID/GamepadConfiguration.cpp:78:53: error: 'LOGICAL_MAXIMUM' was not declared in this scope
   78 |             tempHidReportDescriptor[reportSize++] = LOGICAL_MAXIMUM(1); //0x25;
      |                                                     ^~~~~~~~~~~~~~~
/Users/laurinmichel/Documents/Arduino/libraries/ESP32-BLE-CompositeHID/GamepadConfiguration.cpp:82:53: error: 'REPORT_SIZE' was not declared in this scope
   82 |             tempHidReportDescriptor[reportSize++] = REPORT_SIZE(1); //0x75;
      |                                                     ^~~~~~~~~~~
/Users/laurinmichel/Documents/Arduino/libraries/ESP32-BLE-CompositeHID/GamepadConfiguration.cpp:86:53: error: 'USAGE_MINIMUM' was not declared in this scope
   86 |             tempHidReportDescriptor[reportSize++] = USAGE_MINIMUM(1);//0x19;
      |                                                     ^~~~~~~~~~~~~
/Users/laurinmichel/Documents/Arduino/libraries/ESP32-BLE-CompositeHID/GamepadConfiguration.cpp:90:53: error: 'USAGE_MAXIMUM' was not declared in this scope
   90 |             tempHidReportDescriptor[reportSize++] = USAGE_MAXIMUM(1);//0x29;
      |                                                     ^~~~~~~~~~~~~
/Users/laurinmichel/Documents/Arduino/libraries/ESP32-BLE-CompositeHID/GamepadConfiguration.cpp:94:53: error: 'REPORT_COUNT' was not declared in this scope
   94 |             tempHidReportDescriptor[reportSize++] = REPORT_COUNT(1); //0x95;
      |                                                     ^~~~~~~~~~~~
/Users/laurinmichel/Documents/Arduino/libraries/ESP32-BLE-CompositeHID/GamepadConfiguration.cpp:98:53: error: 'HIDINPUT' was not declared in this scope; did you mean 'INPUT'?
   98 |             tempHidReportDescriptor[reportSize++] = HIDINPUT(1); //0x81;
      |                                                     ^~~~~~~~
      |                                                     INPUT
/Users/laurinmichel/Documents/Arduino/libraries/ESP32-BLE-CompositeHID/GamepadConfiguration.cpp:123:53: error: 'LOGICAL_MINIMUM' was not declared in this scope
  123 |             tempHidReportDescriptor[reportSize++] = LOGICAL_MINIMUM(1); //0x15;
      |                                                     ^~~~~~~~~~~~~~~
/Users/laurinmichel/Documents/Arduino/libraries/ESP32-BLE-CompositeHID/GamepadConfiguration.cpp:127:53: error: 'LOGICAL_MAXIMUM' was not declared in this scope
  127 |             tempHidReportDescriptor[reportSize++] = LOGICAL_MAXIMUM(1); //;0x25;
      |                                                     ^~~~~~~~~~~~~~~
/Users/laurinmichel/Documents/Arduino/libraries/ESP32-BLE-CompositeHID/GamepadConfiguration.cpp:131:53: error: 'REPORT_SIZE' was not declared in this scope
  131 |             tempHidReportDescriptor[reportSize++] = REPORT_SIZE(1); //0x75;
      |                                                     ^~~~~~~~~~~
/Users/laurinmichel/Documents/Arduino/libraries/ESP32-BLE-CompositeHID/GamepadConfiguration.cpp:141:57: error: 'REPORT_COUNT' was not declared in this scope
  141 |                 tempHidReportDescriptor[reportSize++] = REPORT_COUNT(1); //0x95;
      |                                                         ^~~~~~~~~~~~
/Users/laurinmichel/Documents/Arduino/libraries/ESP32-BLE-CompositeHID/GamepadConfiguration.cpp:165:57: error: 'HIDINPUT' was not declared in this scope; did you mean 'INPUT'?
  165 |                 tempHidReportDescriptor[reportSize++] = HIDINPUT(1); //0x81;
      |                                                         ^~~~~~~~
      |                                                         INPUT
/Users/laurinmichel/Documents/Arduino/libraries/ESP32-BLE-CompositeHID/GamepadConfiguration.cpp:176:57: error: 'REPORT_COUNT' was not declared in this scope
  176 |                 tempHidReportDescriptor[reportSize++] = REPORT_COUNT(1); //0x95;
      |                                                         ^~~~~~~~~~~~
/Users/laurinmichel/Documents/Arduino/libraries/ESP32-BLE-CompositeHID/GamepadConfiguration.cpp:217:57: error: 'HIDINPUT' was not declared in this scope; did you mean 'INPUT'?
  217 |                 tempHidReportDescriptor[reportSize++] = HIDINPUT(1); //0x81;
      |                                                         ^~~~~~~~
      |                                                         INPUT
/Users/laurinmichel/Documents/Arduino/libraries/ESP32-BLE-CompositeHID/GamepadConfiguration.cpp:229:57: error: 'REPORT_COUNT' was not declared in this scope
  229 |                 tempHidReportDescriptor[reportSize++] = REPORT_COUNT(1); //0x95;
      |                                                         ^~~~~~~~~~~~
/Users/laurinmichel/Documents/Arduino/libraries/ESP32-BLE-CompositeHID/GamepadConfiguration.cpp:233:57: error: 'HIDINPUT' was not declared in this scope; did you mean 'INPUT'?
  233 |                 tempHidReportDescriptor[reportSize++] = HIDINPUT(1); //0x81;
      |                                                         ^~~~~~~~
      |                                                         INPUT
/Users/laurinmichel/Documents/Arduino/libraries/ESP32-BLE-CompositeHID/GamepadConfiguration.cpp:251:53: error: 'LOGICAL_MINIMUM' was not declared in this scope
  251 |             tempHidReportDescriptor[reportSize++] = LOGICAL_MINIMUM(2); //0x16;
      |                                                     ^~~~~~~~~~~~~~~
/Users/laurinmichel/Documents/Arduino/libraries/ESP32-BLE-CompositeHID/GamepadConfiguration.cpp:260:53: error: 'LOGICAL_MAXIMUM' was not declared in this scope
  260 |             tempHidReportDescriptor[reportSize++] = LOGICAL_MAXIMUM(2);//0x26;
      |                                                     ^~~~~~~~~~~~~~~
/Users/laurinmichel/Documents/Arduino/libraries/ESP32-BLE-CompositeHID/GamepadConfiguration.cpp:269:53: error: 'REPORT_SIZE' was not declared in this scope
  269 |             tempHidReportDescriptor[reportSize++] = REPORT_SIZE(1); //0x75;
      |                                                     ^~~~~~~~~~~
/Users/laurinmichel/Documents/Arduino/libraries/ESP32-BLE-CompositeHID/GamepadConfiguration.cpp:273:53: error: 'REPORT_COUNT' was not declared in this scope
  273 |             tempHidReportDescriptor[reportSize++] = REPORT_COUNT(1); //0x95;
      |                                                     ^~~~~~~~~~~~
/Users/laurinmichel/Documents/Arduino/libraries/ESP32-BLE-CompositeHID/GamepadConfiguration.cpp:337:53: error: 'HIDINPUT' was not declared in this scope; did you mean 'INPUT'?
  337 |             tempHidReportDescriptor[reportSize++] = HIDINPUT(1); //0x81;
      |                                                     ^~~~~~~~
      |                                                     INPUT
/Users/laurinmichel/Documents/Arduino/libraries/ESP32-BLE-CompositeHID/GamepadConfiguration.cpp:341:53: error: 'END_COLLECTION' was not declared in this scope
  341 |             tempHidReportDescriptor[reportSize++] = END_COLLECTION(0); //0xc0;
      |                                                     ^~~~~~~~~~~~~~
/Users/laurinmichel/Documents/Arduino/libraries/ESP32-BLE-CompositeHID/GamepadConfiguration.cpp:352:53: error: 'LOGICAL_MINIMUM' was not declared in this scope
  352 |             tempHidReportDescriptor[reportSize++] = LOGICAL_MINIMUM(2); //0x16;
      |                                                     ^~~~~~~~~~~~~~~
/Users/laurinmichel/Documents/Arduino/libraries/ESP32-BLE-CompositeHID/GamepadConfiguration.cpp:361:53: error: 'LOGICAL_MAXIMUM' was not declared in this scope
  361 |             tempHidReportDescriptor[reportSize++] = LOGICAL_MAXIMUM(2); //0x26;
      |                                                     ^~~~~~~~~~~~~~~
/Users/laurinmichel/Documents/Arduino/libraries/ESP32-BLE-CompositeHID/GamepadConfiguration.cpp:370:53: error: 'REPORT_SIZE' was not declared in this scope
  370 |             tempHidReportDescriptor[reportSize++] = REPORT_SIZE(1); //0x75;
      |                                                     ^~~~~~~~~~~
/Users/laurinmichel/Documents/Arduino/libraries/ESP32-BLE-CompositeHID/GamepadConfiguration.cpp:374:53: error: 'REPORT_COUNT' was not declared in this scope
  374 |             tempHidReportDescriptor[reportSize++] = REPORT_COUNT(1); //0x95;
      |                                                     ^~~~~~~~~~~~
/Users/laurinmichel/Documents/Arduino/libraries/ESP32-BLE-CompositeHID/GamepadConfiguration.cpp:417:53: error: 'HIDINPUT' was not declared in this scope; did you mean 'INPUT'?
  417 |             tempHidReportDescriptor[reportSize++] = HIDINPUT(1); 0x81;
      |                                                     ^~~~~~~~
      |                                                     INPUT
/Users/laurinmichel/Documents/Arduino/libraries/ESP32-BLE-CompositeHID/GamepadConfiguration.cpp:421:53: error: 'END_COLLECTION' was not declared in this scope
  421 |             tempHidReportDescriptor[reportSize++] = END_COLLECTION(0); //0xc0;
      |                                                     ^~~~~~~~~~~~~~
/Users/laurinmichel/Documents/Arduino/libraries/ESP32-BLE-CompositeHID/GamepadConfiguration.cpp:444:53: error: 'LOGICAL_MINIMUM' was not declared in this scope
  444 |             tempHidReportDescriptor[reportSize++] = LOGICAL_MINIMUM(1); //0x15;
      |                                                     ^~~~~~~~~~~~~~~
/Users/laurinmichel/Documents/Arduino/libraries/ESP32-BLE-CompositeHID/GamepadConfiguration.cpp:448:53: error: 'LOGICAL_MAXIMUM' was not declared in this scope
  448 |             tempHidReportDescriptor[reportSize++] = LOGICAL_MAXIMUM(1); //0x25;
      |                                                     ^~~~~~~~~~~~~~~
/Users/laurinmichel/Documents/Arduino/libraries/ESP32-BLE-CompositeHID/GamepadConfiguration.cpp:452:53: error: 'PHYSICAL_MINIMUM' was not declared in this scope
  452 |             tempHidReportDescriptor[reportSize++] = PHYSICAL_MINIMUM(1); //0x35;
      |                                                     ^~~~~~~~~~~~~~~~
/Users/laurinmichel/Documents/Arduino/libraries/ESP32-BLE-CompositeHID/GamepadConfiguration.cpp:456:53: error: 'PHYSICAL_MAXIMUM' was not declared in this scope
  456 |             tempHidReportDescriptor[reportSize++] = PHYSICAL_MAXIMUM(2); //0x46;
      |                                                     ^~~~~~~~~~~~~~~~
/Users/laurinmichel/Documents/Arduino/libraries/ESP32-BLE-CompositeHID/GamepadConfiguration.cpp:461:53: error: 'UNIT' was not declared in this scope
  461 |             tempHidReportDescriptor[reportSize++] = UNIT(1); //0x65;
      |                                                     ^~~~
/Users/laurinmichel/Documents/Arduino/libraries/ESP32-BLE-CompositeHID/GamepadConfiguration.cpp:465:53: error: 'REPORT_SIZE' was not declared in this scope
  465 |             tempHidReportDescriptor[reportSize++] = REPORT_SIZE(1); //0x75;
      |                                                     ^~~~~~~~~~~
/Users/laurinmichel/Documents/Arduino/libraries/ESP32-BLE-CompositeHID/GamepadConfiguration.cpp:469:53: error: 'REPORT_COUNT' was not declared in this scope
  469 |             tempHidReportDescriptor[reportSize++] = REPORT_COUNT(1); //0x95;
      |                                                     ^~~~~~~~~~~~
/Users/laurinmichel/Documents/Arduino/libraries/ESP32-BLE-CompositeHID/GamepadConfiguration.cpp:473:53: error: 'HIDINPUT' was not declared in this scope; did you mean 'INPUT'?
  473 |             tempHidReportDescriptor[reportSize++] = HIDINPUT(1); //0x81;
      |                                                     ^~~~~~~~
      |                                                     INPUT
/Users/laurinmichel/Documents/Arduino/libraries/ESP32-BLE-CompositeHID/GamepadConfiguration.cpp:477:53: error: 'END_COLLECTION' was not declared in this scope
  477 |             tempHidReportDescriptor[reportSize++] = END_COLLECTION(0); //0xc0;
      |                                                     ^~~~~~~~~~~~~~
/Users/laurinmichel/Documents/Arduino/libraries/ESP32-BLE-CompositeHID/GamepadConfiguration.cpp:496:53: error: 'USAGE_MINIMUM' was not declared in this scope
  496 |             tempHidReportDescriptor[reportSize++] = USAGE_MINIMUM(1); // Usage minimum
      |                                                     ^~~~~~~~~~~~~
/Users/laurinmichel/Documents/Arduino/libraries/ESP32-BLE-CompositeHID/GamepadConfiguration.cpp:499:53: error: 'USAGE_MAXIMUM' was not declared in this scope
  499 |             tempHidReportDescriptor[reportSize++] = USAGE_MAXIMUM(1); // Usage maximum
      |                                                     ^~~~~~~~~~~~~
/Users/laurinmichel/Documents/Arduino/libraries/ESP32-BLE-CompositeHID/GamepadConfiguration.cpp:502:53: error: 'LOGICAL_MINIMUM' was not declared in this scope
  502 |             tempHidReportDescriptor[reportSize++] = LOGICAL_MINIMUM(1); // Logical minimum
      |                                                     ^~~~~~~~~~~~~~~
/Users/laurinmichel/Documents/Arduino/libraries/ESP32-BLE-CompositeHID/GamepadConfiguration.cpp:505:53: error: 'LOGICAL_MAXIMUM' was not declared in this scope
  505 |             tempHidReportDescriptor[reportSize++] = LOGICAL_MAXIMUM(1); // Logical maximum
      |                                                     ^~~~~~~~~~~~~~~
/Users/laurinmichel/Documents/Arduino/libraries/ESP32-BLE-CompositeHID/GamepadConfiguration.cpp:508:53: error: 'REPORT_COUNT' was not declared in this scope
  508 |             tempHidReportDescriptor[reportSize++] = REPORT_COUNT(1); // Report count - 8 bits
      |                                                     ^~~~~~~~~~~~
/Users/laurinmichel/Documents/Arduino/libraries/ESP32-BLE-CompositeHID/GamepadConfiguration.cpp:511:53: error: 'REPORT_SIZE' was not declared in this scope
  511 |             tempHidReportDescriptor[reportSize++] = REPORT_SIZE(1);  // Report size
      |                                                     ^~~~~~~~~~~
/Users/laurinmichel/Documents/Arduino/libraries/ESP32-BLE-CompositeHID/GamepadConfiguration.cpp:514:53: error: 'HIDOUTPUT' was not declared in this scope; did you mean 'OUTPUT'?
  514 |             tempHidReportDescriptor[reportSize++] = HIDOUTPUT(1); // Output
      |                                                     ^~~~~~~~~
      |                                                     OUTPUT
/Users/laurinmichel/Documents/Arduino/libraries/ESP32-BLE-CompositeHID/GamepadConfiguration.cpp:517:53: error: 'END_COLLECTION' was not declared in this scope
  517 |             tempHidReportDescriptor[reportSize++] = END_COLLECTION(0); // End physical collection
      |                                                     ^~~~~~~~~~~~~~
/Users/laurinmichel/Documents/Arduino/libraries/ESP32-BLE-CompositeHID/GamepadConfiguration.cpp:522:45: error: 'END_COLLECTION' was not declared in this scope
  522 |     tempHidReportDescriptor[reportSize++] = END_COLLECTION(0); //0xc0;
      |                                             ^~~~~~~~~~~~~~
/Users/laurinmichel/Documents/Arduino/libraries/ESP32-BLE-CompositeHID/MouseDevice.cpp: In member function 'virtual void MouseDevice::init(NimBLEHIDDevice*)':
/Users/laurinmichel/Documents/Arduino/libraries/ESP32-BLE-CompositeHID/MouseDevice.cpp:28:29: error: 'class NimBLEHIDDevice' has no member named 'inputReport'; did you mean 'getInputReport'?
   28 |     setCharacteristics(hid->inputReport(_config.getReportId()), nullptr);
      |                             ^~~~~~~~~~~
      |                             getInputReport
/Users/laurinmichel/Documents/Arduino/libraries/ESP32-BLE-CompositeHID/MouseConfiguration.cpp: In member function 'virtual size_t MouseConfiguration::makeDeviceReport(uint8_t*, size_t) const':
/Users/laurinmichel/Documents/Arduino/libraries/ESP32-BLE-CompositeHID/MouseConfiguration.cpp:33:58: error: 'USAGE_PAGE' was not declared in this scope
   33 |     tempHidReportDescriptor[hidReportDescriptorSize++] = USAGE_PAGE(1);
      |                                                          ^~~~~~~~~~
/Users/laurinmichel/Documents/Arduino/libraries/ESP32-BLE-CompositeHID/MouseConfiguration.cpp:36:58: error: 'USAGE' was not declared in this scope
   36 |     tempHidReportDescriptor[hidReportDescriptorSize++] = USAGE(1);
      |                                                          ^~~~~
/Users/laurinmichel/Documents/Arduino/libraries/ESP32-BLE-CompositeHID/MouseConfiguration.cpp:39:58: error: 'COLLECTION' was not declared in this scope
   39 |     tempHidReportDescriptor[hidReportDescriptorSize++] = COLLECTION(1);
      |                                                          ^~~~~~~~~~
/Users/laurinmichel/Documents/Arduino/libraries/ESP32-BLE-CompositeHID/MouseConfiguration.cpp:48:58: error: 'REPORT_ID' was not declared in this scope
   48 |     tempHidReportDescriptor[hidReportDescriptorSize++] = REPORT_ID(1);
      |                                                          ^~~~~~~~~
/Users/laurinmichel/Documents/Arduino/libraries/ESP32-BLE-CompositeHID/MouseConfiguration.cpp:57:62: error: 'USAGE_MINIMUM' was not declared in this scope
   57 |         tempHidReportDescriptor[hidReportDescriptorSize++] = USAGE_MINIMUM(1);
      |                                                              ^~~~~~~~~~~~~
/Users/laurinmichel/Documents/Arduino/libraries/ESP32-BLE-CompositeHID/MouseConfiguration.cpp:60:62: error: 'USAGE_MAXIMUM' was not declared in this scope
   60 |         tempHidReportDescriptor[hidReportDescriptorSize++] = USAGE_MAXIMUM(1);
      |                                                              ^~~~~~~~~~~~~
/Users/laurinmichel/Documents/Arduino/libraries/ESP32-BLE-CompositeHID/MouseConfiguration.cpp:63:62: error: 'LOGICAL_MINIMUM' was not declared in this scope
   63 |         tempHidReportDescriptor[hidReportDescriptorSize++] = LOGICAL_MINIMUM(1);
      |                                                              ^~~~~~~~~~~~~~~
/Users/laurinmichel/Documents/Arduino/libraries/ESP32-BLE-CompositeHID/MouseConfiguration.cpp:66:62: error: 'LOGICAL_MAXIMUM' was not declared in this scope
   66 |         tempHidReportDescriptor[hidReportDescriptorSize++] = LOGICAL_MAXIMUM(1);
      |                                                              ^~~~~~~~~~~~~~~
/Users/laurinmichel/Documents/Arduino/libraries/ESP32-BLE-CompositeHID/MouseConfiguration.cpp:69:62: error: 'REPORT_SIZE' was not declared in this scope
   69 |         tempHidReportDescriptor[hidReportDescriptorSize++] = REPORT_SIZE(1);
      |                                                              ^~~~~~~~~~~
/Users/laurinmichel/Documents/Arduino/libraries/ESP32-BLE-CompositeHID/MouseConfiguration.cpp:72:62: error: 'REPORT_COUNT' was not declared in this scope
   72 |         tempHidReportDescriptor[hidReportDescriptorSize++] = REPORT_COUNT(1);
      |                                                              ^~~~~~~~~~~~
/Users/laurinmichel/Documents/Arduino/libraries/ESP32-BLE-CompositeHID/MouseConfiguration.cpp:75:62: error: 'HIDINPUT' was not declared in this scope; did you mean 'INPUT'?
   75 |         tempHidReportDescriptor[hidReportDescriptorSize++] = HIDINPUT(1);
      |                                                              ^~~~~~~~
      |                                                              INPUT
/Users/laurinmichel/Documents/Arduino/libraries/ESP32-BLE-CompositeHID/MouseConfiguration.cpp:109:62: error: 'LOGICAL_MINIMUM' was not declared in this scope
  109 |         tempHidReportDescriptor[hidReportDescriptorSize++] = LOGICAL_MINIMUM(1);
      |                                                              ^~~~~~~~~~~~~~~
/Users/laurinmichel/Documents/Arduino/libraries/ESP32-BLE-CompositeHID/MouseConfiguration.cpp:112:62: error: 'LOGICAL_MAXIMUM' was not declared in this scope
  112 |         tempHidReportDescriptor[hidReportDescriptorSize++] = LOGICAL_MAXIMUM(1);
      |                                                              ^~~~~~~~~~~~~~~
/Users/laurinmichel/Documents/Arduino/libraries/ESP32-BLE-CompositeHID/MouseConfiguration.cpp:115:62: error: 'REPORT_SIZE' was not declared in this scope
  115 |         tempHidReportDescriptor[hidReportDescriptorSize++] = REPORT_SIZE(1);
      |                                                              ^~~~~~~~~~~
/Users/laurinmichel/Documents/Arduino/libraries/ESP32-BLE-CompositeHID/MouseConfiguration.cpp:118:62: error: 'REPORT_COUNT' was not declared in this scope
  118 |         tempHidReportDescriptor[hidReportDescriptorSize++] = REPORT_COUNT(1);
      |                                                              ^~~~~~~~~~~~
/Users/laurinmichel/Documents/Arduino/libraries/ESP32-BLE-CompositeHID/MouseConfiguration.cpp:121:62: error: 'HIDINPUT' was not declared in this scope; did you mean 'INPUT'?
  121 |         tempHidReportDescriptor[hidReportDescriptorSize++] = HIDINPUT(1);
      |                                                              ^~~~~~~~
      |                                                              INPUT
/Users/laurinmichel/Documents/Arduino/libraries/ESP32-BLE-CompositeHID/MouseConfiguration.cpp:149:58: error: 'END_COLLECTION' was not declared in this scope
  149 |     tempHidReportDescriptor[hidReportDescriptorSize++] = END_COLLECTION(0); //0xc0;
      |                                                          ^~~~~~~~~~~~~~
/Users/laurinmichel/Documents/Arduino/libraries/ESP32-BLE-CompositeHID/KeyboardDevice.cpp: In member function 'virtual void KeyboardDevice::init(NimBLEHIDDevice*)':
/Users/laurinmichel/Documents/Arduino/libraries/ESP32-BLE-CompositeHID/KeyboardDevice.cpp:68:19: error: 'class NimBLEHIDDevice' has no member named 'inputReport'; did you mean 'getInputReport'?
   68 |     _input = hid->inputReport(_config.getReportId());
      |                   ^~~~~~~~~~~
      |                   getInputReport
/Users/laurinmichel/Documents/Arduino/libraries/ESP32-BLE-CompositeHID/KeyboardDevice.cpp:69:24: error: 'class NimBLEHIDDevice' has no member named 'inputReport'; did you mean 'getInputReport'?
   69 |     _mediaInput = hid->inputReport(MEDIA_KEYS_REPORT_ID);
      |                        ^~~~~~~~~~~
      |                        getInputReport
/Users/laurinmichel/Documents/Arduino/libraries/ESP32-BLE-CompositeHID/KeyboardDevice.cpp:70:20: error: 'class NimBLEHIDDevice' has no member named 'outputReport'; did you mean 'getOutputReport'?
   70 |     _output = hid->outputReport(_config.getReportId());
      |                    ^~~~~~~~~~~~
      |                    getOutputReport

exit status 1

Compilation error: exit status 1
```

**Comment by cflixdev-projects** [comment]
The latest version of NimBLE includes additional features, which, despite containing the necessary commit, may still cause issues. To fix this, download version [1.4.0](https://github.com/h2zero/NimBLE-Arduino/tree/a79941cc9e77ed60136ee385b1c73d89c847bd94) as a ZIP file, extract it, and move the folder to your Arduino libraries directory (e.g., C:\Users\XXXXX\Documents\Arduino\libraries, or wherever your libraries are stored. You can also just install v1.4.0 in the Arduino Library.

**Comment by Laurin08** [comment]
Hi
Thanks again, I was able to clear the error with adding `#include <stdexcept>` in the GamepadDevice.cpp file. now it works with the 2.0.0 version of nimble

**Comment by Mystfit** [comment]
> Hi Thanks again, I was able to clear the error with adding `#include <stdexcept>` in the GamepadDevice.cpp file. now it works with the 2.0.0 version of nimble

I've merged in the latest NimBLE 2.1 support from #23. You should now be able to use the latest release version of NimBLE rather than relying on a specific commit.

**Comment by Laurin08** [comment]
Hi 
Ive got the same problem again, with " compositeHID.end();" 
But this time there are no errors but the controller crashes....
do you have an idea what the problem could be?
I tried it with different Nimble versions
